# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bc3a45e45971bc4dec64f715f5b1e5bbc0bf5582e268e54a3b2d8d3a0f2c1b99f92e3a233c6995ec3000b13ace2a18ad2ae43f0e40af3e269b637638935a223

test:
  secret_key_base: bc758289a8412f19622d9710368a86b2a6f0191c8a4c8466719c1351435f1d902f609b60e8fa032730748ae665e8d769ee1e0ebd6a5e78afd0d9da65d28041f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
